"""add is_admin to users

Revision ID: 45741f4c9e40
Revises: 88a8dbd990ef
Create Date: 2026-09-02 15:10:50.255966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45741f4c9e40"
down_revision = "88a8dbd990ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_admin",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
